const { Sequelize } = require('sequelize');
const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });


function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}
module.exports = {
	ALIVE_MSG: process.env.ALIVE_MSG === undefined ? 'default' : process.env.ALIVE_MSG,
	ANTI_SPAM: process.env.ANTI_SPAM === undefined ? 'true' : process.env.ANTI_SPAM,
	INBOX_BL_MSG: process.env.INBOX_BL_MSG === undefined ? '*Join Group And Use*  https://chat.whatsapp.com/BX3gOr5YB5v0LkDFkqY9Ov' : process.env.INBOX_BL_MSG,
        ANTI_BAD: process.env.ANTI_BAD === undefined ? 'true' : process.env.ANTI_BAD,
        AUTO_REACT: process.env.AUTO_REACT === undefined ? 'true' : process.env.AUTO_REACT,
	sessionName: process.env.SESSION_ID || 'U2FsdGVkX1/XfDeZBm8Bv_S-E-C-K-T-O-R_Mv_S-E-C-K-T-O-R_eheLBDeTdUUX7zBPA948=',
	ANTI_LINK: process.env.ANTI_LINK || 'true',
	ALIVE_LOGO: process.env.ALIVE_LOGO === undefined ? 'https://cdn.vox-cdn.com/thumbor/IBcc0fxI74BMJOSe94CTI0hPZyE=/0x40:1024x723/1200x800/filters:focal(0x40:1024x723)/cdn.vox-cdn.com/uploads/chorus_image/image/48851561/6821369-astro-boy.0.0.jpg' : process.env.ALIVE_LOGO,
        FOOTER: process.env.FOOTER === undefined ? 'Astro-MD' : process.env.FOOTER,
	BUTTON: process.env.BUTTON === undefined ? 'Youtube' : process.env.BUTTON,
	BUTTONURL: process.env.BUTTON_URL === undefined ? 'youtube.com/hjwn7skv' : process.env.BUTTONURL,
	onlygroup: process.env.onlygroup === undefined ? 'true' : process.env.onlygroup,
	OWNER_NAME: process.env.OWNER_NAME === undefined ? 'VihangaYT' : process.env.OWNER_NAME,
	OWNER_NUMBER: process.env.OWNER_NUMBER === undefined ? '99999999' : process.env.OWNER_NUMBER,
	SONG_DOWN: process.env.SONG_DOWN === undefined ? 'Downloading Your Song...' : process.env.SONG_DOWN,
	SONG_UP: process.env.SONG_UP === undefined ? 'Uploading Your Song...' : process.env.SONG_UP,
	VIDEO_DOWN: process.env.VIDEO_DOWN === undefined ? 'Downloading Your Video...' : process.env.VIDEO_DOWN,
	VIDEO_UP: process.env.VIDEO_UP === undefined ? 'Uploading Your Video...' : process.env.VIDEO_UP,
	CAPTION: process.env.CAPTION === undefined ? 'Generated By Astro-MD' : process.env.CAPTION,
	FILE_DOWN: process.env.FILE_DOWN === undefined ? 'Downloading Your File...' : process.env.FILE_DOWN,
	FILE_UP: process.env.FILE_UP === undefined ? 'Uploading Your File...' : process.env.FILE_UP,
};
